In [7]:
import requests
import pandas as pd
import json

In [8]:
url = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-college-effectifs-niveau-sexe-lv/records"

params = {    
    "offset": 0
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.json())

200

In [9]:
data = response.json()

print(data.keys())
print(data["results"][0])

dict_keys(['total_count', 'results'])
{'rentree_scolaire': '2019-01-01', 'code_region_academique': '00', 'code_region_insee': '00', 'region_academique': 'OUTRE-MER HORS REGIONS ACADEMIQUES', 'code_aca': '40', 'academie': 'NOUVELLE CALEDONIE', 'code_dept': '988', 'departement': 'NOUVELLE CALEDONIE', 'code_commune': '98805', 'commune': 'DUMBEA', 'numero_college': '9830681Y', 'denomination_principale': 'COLLEGE', 'patronyme': 'DE DUMBEA SUR MER 1', 'secteur': 'PUBLIC', 'rep': 0, 'rep0': 0, 'nombre_eleves_total': 549, 'nombre_d_eleves_total_hors_segpa_hors_ulis': 545, 'nombre_d_eleves_total_segpa': 0, 'nombre_d_eleves_total_ulis': 4, 'nombre_total_de_6emes': 149, 'nombre_de_6emes_hors_segpa_hors_ulis': 148, 'nombre_de_6emes_segpa': 0, 'nombre_de_6emes_ulis': 1, '6eme_filles': 92, '6emes_garcons': 57, 'nombre_de_6emes_lv1_allemand': 0, 'nombre_de_6emes_lv1_anglais': 149, 'nombre_de_6emes_lv1_espagnol': 0, 'nombre_de_6emes_lv1_autres_langues': 0, 'nombre_de_6emes_lv2_allemand': 0, 'nombre_de_6emes_lv2_anglais': 0, 'nombre_de_6emes_lv2_espagnol': 0, 'nombre_de_6emes_lv2_italien': 0, 'nombre_de_6emes_lv2_autres_langues': 0, 'nombre_total_de_5emes': 131, 'nombre_de_5emes_hors_segpa_hors_ulis': 129, 'nombre_de_5emes_segpa': 0, 'nombre_de_5emes_ulis': 2, '5eme_filles': 82, '5emes_garcons': 49, 'nombre_de_5emes_lv1_allemand': 0, 'nombre_de_5emes_lv1_anglais': 131, 'nombre_de_5emes_lv1_espagnol': 0, 'nombre_de_5emes_lv1_autres_langues': 0, 'nombre_de_5emes_lv2_allemand': 0, 'nombre_de_5emes_lv2_anglais': 0, 'nombre_de_5emes_lv2_espagnol': 83, 'nombre_de_5emes_lv2_italien': 0, 'nombre_de_5emes_lv2_autres_langues': 48, 'nombre_total_de_4emes': 129, 'nombre_de_4emes_hors_segpa_hors_ulis': 128, 'nombre_de_4emes_segpa': 0, 'nombre_de_4emes_ulis': 1, '4eme_filles': 64, '4emes_garcons': 65, 'nombre_de_4emes_lv1_allemand': 0, 'nombre_de_4emes_lv1_anglais': 129, 'nombre_de_4emes_lv1_espagnol': 0, 'nombre_de_4emes_lv1_autres_langues': 0, 'nombre_de_4emes_lv2_allemand': 0, 'nombre_de_4emes_lv2_anglais': 0, 'nombre_de_4emes_lv2_espagnol': 85, 'nombre_de_4emes_lv2_italien': 0, 'nombre_de_4emes_lv2_autres_langues': 44, 'nombre_total_de_3emes': 140, 'nombre_de_3emes_hors_segpa_hors_ulis': 140, 'nombre_de_3emes_segpa': 0, 'nombre_de_3emes_ulis': 0, '3eme_filles': 66, '3emes_garcons': 74, 'nombre_de_3emes_lv1_allemand': 0, 'nombre_de_3emes_lv1_anglais': 140, 'nombre_de_3emes_lv1_espagnol': 0, 'nombre_de_3emes_lv1_autres_langues': 0, 'nombre_de_3emes_lv2_allemand': 0, 'nombre_de_3emes_lv2_anglais': 0, 'nombre_de_3emes_lv2_espagnol': 122, 'nombre_de_3emes_lv2_italien': 0, 'nombre_de_3emes_lv2_autres_langues': 18, 'num_ligne': 8}

In [10]:
df = pd.DataFrame(data["results"])

print(df.head())
print(df.columns.tolist())

  rentree_scolaire code_region_academique code_region_insee  \
0       2019-01-01                     00                00
1       2019-01-01                     00                00
2       2019-01-01                     00                00
3       2019-01-01                     00                00
4       2019-01-01                     00                00

                    region_academique code_aca            academie code_dept  \
0  OUTRE-MER HORS REGIONS ACADEMIQUES       40  NOUVELLE CALEDONIE       988
1  OUTRE-MER HORS REGIONS ACADEMIQUES       40  NOUVELLE CALEDONIE       988
2  OUTRE-MER HORS REGIONS ACADEMIQUES       40  NOUVELLE CALEDONIE       988
3  OUTRE-MER HORS REGIONS ACADEMIQUES       40  NOUVELLE CALEDONIE       988
4  OUTRE-MER HORS REGIONS ACADEMIQUES       40  NOUVELLE CALEDONIE       988

          departement code_commune    commune  ...  \
0  NOUVELLE CALEDONIE        98805     DUMBEA  ...
1  NOUVELLE CALEDONIE        98807  HIENGHENE  ...
2  NOUVELLE CALEDONIE        98808   HOUAILOU  ...
3  NOUVELLE CALEDONIE        98808   HOUAILOU  ...
4  NOUVELLE CALEDONIE        98812     KOUMAC  ...

  nombre_de_3emes_lv1_allemand nombre_de_3emes_lv1_anglais  \
0                            0                         140
1                            0                          31
2                            0                          10
3                            0                          32
4                            0                          93

  nombre_de_3emes_lv1_espagnol nombre_de_3emes_lv1_autres_langues  \
0                            0                                  0
1                            0                                  0
2                            0                                  0
3                            0                                  0
4                            0                                  0

   nombre_de_3emes_lv2_allemand  nombre_de_3emes_lv2_anglais  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             0                            0
4                             0                            0

   nombre_de_3emes_lv2_espagnol  nombre_de_3emes_lv2_italien  \
0                           122                            0
1                            31                            0
2                            10                            0
3                            22                            0
4                            93                            0

   nombre_de_3emes_lv2_autres_langues  num_ligne
0                                  18          8
1                                   0         10
2                                   0         11
3                                  10         12
4                                   0         17

[5 rows x 81 columns]
['rentree_scolaire', 'code_region_academique', 'code_region_insee', 'region_academique', 'code_aca', 'academie', 'code_dept', 'departement', 'code_commune', 'commune', 'numero_college', 'denomination_principale', 'patronyme', 'secteur', 'rep', 'rep0', 'nombre_eleves_total', 'nombre_d_eleves_total_hors_segpa_hors_ulis', 'nombre_d_eleves_total_segpa', 'nombre_d_eleves_total_ulis', 'nombre_total_de_6emes', 'nombre_de_6emes_hors_segpa_hors_ulis', 'nombre_de_6emes_segpa', 'nombre_de_6emes_ulis', '6eme_filles', '6emes_garcons', 'nombre_de_6emes_lv1_allemand', 'nombre_de_6emes_lv1_anglais', 'nombre_de_6emes_lv1_espagnol', 'nombre_de_6emes_lv1_autres_langues', 'nombre_de_6emes_lv2_allemand', 'nombre_de_6emes_lv2_anglais', 'nombre_de_6emes_lv2_espagnol', 'nombre_de_6emes_lv2_italien', 'nombre_de_6emes_lv2_autres_langues', 'nombre_total_de_5emes', 'nombre_de_5emes_hors_segpa_hors_ulis', 'nombre_de_5emes_segpa', 'nombre_de_5emes_ulis', '5eme_filles', '5emes_garcons', 'nombre_de_5emes_lv1_allemand', 'nombre_de_5emes_lv1_anglais', 'nombre_de_5emes_lv1_espagnol', 'nombre_de_5emes_lv1_autres_langues', 'nombre_de_5emes_lv2_allemand', 'nombre_de_5emes_lv2_anglais', 'nombre_de_5emes_lv2_espagnol', 'nombre_de_5emes_lv2_italien', 'nombre_de_5emes_lv2_autres_langues', 'nombre_total_de_4emes', 'nombre_de_4emes_hors_segpa_hors_ulis', 'nombre_de_4emes_segpa', 'nombre_de_4emes_ulis', '4eme_filles', '4emes_garcons', 'nombre_de_4emes_lv1_allemand', 'nombre_de_4emes_lv1_anglais', 'nombre_de_4emes_lv1_espagnol', 'nombre_de_4emes_lv1_autres_langues', 'nombre_de_4emes_lv2_allemand', 'nombre_de_4emes_lv2_anglais', 'nombre_de_4emes_lv2_espagnol', 'nombre_de_4emes_lv2_italien', 'nombre_de_4emes_lv2_autres_langues', 'nombre_total_de_3emes', 'nombre_de_3emes_hors_segpa_hors_ulis', 'nombre_de_3emes_segpa', 'nombre_de_3emes_ulis', '3eme_filles', '3emes_garcons', 'nombre_de_3emes_lv1_allemand', 'nombre_de_3emes_lv1_anglais', 'nombre_de_3emes_lv1_espagnol', 'nombre_de_3emes_lv1_autres_langues', 'nombre_de_3emes_lv2_allemand', 'nombre_de_3emes_lv2_anglais', 'nombre_de_3emes_lv2_espagnol', 'nombre_de_3emes_lv2_italien', 'nombre_de_3emes_lv2_autres_langues', 'num_ligne']

In [11]:
url = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-college-effectifs-niveau-sexe-lv/records"

response = requests.get(url, params=params)
data = response.json()

print(data["results"][0].keys())

dict_keys(['rentree_scolaire', 'code_region_academique', 'code_region_insee', 'region_academique', 'code_aca', 'academie', 'code_dept', 'departement', 'code_commune', 'commune', 'numero_college', 'denomination_principale', 'patronyme', 'secteur', 'rep', 'rep0', 'nombre_eleves_total', 'nombre_d_eleves_total_hors_segpa_hors_ulis', 'nombre_d_eleves_total_segpa', 'nombre_d_eleves_total_ulis', 'nombre_total_de_6emes', 'nombre_de_6emes_hors_segpa_hors_ulis', 'nombre_de_6emes_segpa', 'nombre_de_6emes_ulis', '6eme_filles', '6emes_garcons', 'nombre_de_6emes_lv1_allemand', 'nombre_de_6emes_lv1_anglais', 'nombre_de_6emes_lv1_espagnol', 'nombre_de_6emes_lv1_autres_langues', 'nombre_de_6emes_lv2_allemand', 'nombre_de_6emes_lv2_anglais', 'nombre_de_6emes_lv2_espagnol', 'nombre_de_6emes_lv2_italien', 'nombre_de_6emes_lv2_autres_langues', 'nombre_total_de_5emes', 'nombre_de_5emes_hors_segpa_hors_ulis', 'nombre_de_5emes_segpa', 'nombre_de_5emes_ulis', '5eme_filles', '5emes_garcons', 'nombre_de_5emes_lv1_allemand', 'nombre_de_5emes_lv1_anglais', 'nombre_de_5emes_lv1_espagnol', 'nombre_de_5emes_lv1_autres_langues', 'nombre_de_5emes_lv2_allemand', 'nombre_de_5emes_lv2_anglais', 'nombre_de_5emes_lv2_espagnol', 'nombre_de_5emes_lv2_italien', 'nombre_de_5emes_lv2_autres_langues', 'nombre_total_de_4emes', 'nombre_de_4emes_hors_segpa_hors_ulis', 'nombre_de_4emes_segpa', 'nombre_de_4emes_ulis', '4eme_filles', '4emes_garcons', 'nombre_de_4emes_lv1_allemand', 'nombre_de_4emes_lv1_anglais', 'nombre_de_4emes_lv1_espagnol', 'nombre_de_4emes_lv1_autres_langues', 'nombre_de_4emes_lv2_allemand', 'nombre_de_4emes_lv2_anglais', 'nombre_de_4emes_lv2_espagnol', 'nombre_de_4emes_lv2_italien', 'nombre_de_4emes_lv2_autres_langues', 'nombre_total_de_3emes', 'nombre_de_3emes_hors_segpa_hors_ulis', 'nombre_de_3emes_segpa', 'nombre_de_3emes_ulis', '3eme_filles', '3emes_garcons', 'nombre_de_3emes_lv1_allemand', 'nombre_de_3emes_lv1_anglais', 'nombre_de_3emes_lv1_espagnol', 'nombre_de_3emes_lv1_autres_langues', 'nombre_de_3emes_lv2_allemand', 'nombre_de_3emes_lv2_anglais', 'nombre_de_3emes_lv2_espagnol', 'nombre_de_3emes_lv2_italien', 'nombre_de_3emes_lv2_autres_langues', 'num_ligne'])

In [12]:
url = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-college-effectifs-niveau-sexe-lv/records"

params = {
    "where": "code_dept='69'",
    "limit": None
}

response = requests.get(url, params=params)

data = response.json()["results"]

df = pd.DataFrame(data)

print(df[[
    "numero_college",
    "denomination_principale",
    "commune",
    "code_commune",
    "nombre_eleves_total"
]])

  numero_college    denomination_principale                  commune  \
0       0692582G                    COLLEGE                 BRIGNAIS
1       0693890D                    COLLEGE                  BRINDAS
2       0690010L       LP LYCEE DES METIERS                     BRON
3       0693365H                    COLLEGE                CHAPONOST
4       0692448L                    COLLEGE        CHAZAY-D'AZERGUES
5       0690510E              COLLEGE PRIVE                   ECULLY
6       0691465T  LYCEE PROFESSIONNEL PRIVE                   GIVORS
7       0690611P              COLLEGE PRIVE                  MORNANT
8       0692346A                    COLLEGE                  MORNANT
9       0690078K                    COLLEGE  SAINTE-FOY-L'ARGENTIERE

  code_commune  nombre_eleves_total
0        69027                  435
1        69028                  671
2        69029                   22
3        69043                  451
4        69052                  631
5        69081                  733
6        69091                   20
7        69141                  490
8        69141                  575
9        69201                  441

In [13]:
url = "https://geo.api.gouv.fr/departements"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data)

print(df.head())

                       nom code codeRegion
0                      Ain   01         84
1                    Aisne   02         32
2                   Allier   03         84
3  Alpes-de-Haute-Provence   04         93
4             Hautes-Alpes   05         93

In [14]:
departements = requests.get(
    "https://geo.api.gouv.fr/departements"
).json()

regions = requests.get(
    "https://geo.api.gouv.fr/regions"
).json()

df_dep = pd.DataFrame(departements)
df_reg = pd.DataFrame(regions)

print(df_dep.columns)
print(df_reg.columns)

Index(['nom', 'code', 'codeRegion'], dtype='str')
Index(['nom', 'code'], dtype='str')

In [15]:
url = "https://geo.api.gouv.fr/communes?fields=nom,code,codeDepartement,population&format=json"

data = requests.get(url).json()

df = pd.DataFrame(data)

#print(df.head())
df

                           nom   code codeDepartement  population
0      L'Abergement-Clémenciat  01001              01       860.0
1        L'Abergement-de-Varey  01002              01       270.0
2            Ambérieu-en-Bugey  01004              01     15934.0
3          Ambérieux-en-Dombes  01005              01      1906.0
4                      Ambléon  01006              01       115.0
...                        ...    ...             ...         ...
34964                    Touho  98830             988      2284.0
34965                      Voh  98831             988      3122.0
34966                     Yaté  98832             988      1588.0
34967                  Kouaoua  98833             988      1335.0
34968        Île de Clipperton  98901             989         NaN

[34969 rows x 4 columns]

In [22]:
url = "https://api-lannuaire.service-public.gouv.fr/api/explore/v2.1/catalog/datasets/api-lannuaire-administration/records"

params = {
    "limit": 5,
    "where": 'nom like "Mairie%"'
}

response = requests.get(url, params=params)
data = response.json()["results"]

rows = []

for item in data:
    adresse = json.loads(item["adresse"])[0] if item.get("adresse") else {}

    rows.append({
        "code_insee": item.get("code_insee_commune"),
        "nom": item.get("nom"),
        "adresse": adresse.get("numero_voie"),
        "code_postal": adresse.get("code_postal"),
        "commune": adresse.get("nom_commune"),
        "latitude": adresse.get("latitude"),
        "longitude": adresse.get("longitude"),
        "email": item.get("adresse_courriel"),
    })

df = pd.DataFrame(rows)

#print(df.head())
df

,code_insee,nom,adresse,code_postal,commune,latitude,longitude,email
0,69123,Mairie - Lyon - Mairie centrale,Place de la Comédie,69001,Lyon,45.7676905,4.8353706,NaN
1,29070,Mairie - Mairie - Guiler-sur-Goyen,2 Hent Park Meilar,29710,Guiler-sur-Goyen,48.016505,-4.357696,mairie@guiler-sur-goyen.bzh
2,25475,Mairie - Quingey,Place d'Armes,25440,Quingey,47.103099823,5.88290977478,mairie-quingey@orange.fr
3,07318,Mairie - Tauriers,1 place des Sarpe-Bruges,07110,Tauriers,44.5522918701,4.28076410294,mairie.tauriers@wanadoo.fr
4,67151,Mairie - Gambsheim,18 route du Rhin,67760,Gambsheim,48.69197,7.886555,mairie@mairie-gambsheim.fr

In [17]:
import requests

url = (
    "https://data.education.gouv.fr/api/explore/v2.1/catalog/"
    "datasets/fr-en-lycee_gt-effectifs-niveau-sexe-lv/records"
)

response = requests.get(
    url,
    params={        
        "offset": 0
    }
)

print(response.status_code)

data = response.json()

print(data.keys())

200
dict_keys(['total_count', 'results'])

In [18]:
import pandas as pd

df = pd.DataFrame(data["results"])

print(
    df[
        [
            "numero_lycee",
            "denomination_principale",
            "patronyme",
            "code_commune",
            "commune",
            "nombre_d_eleves",
            "rentree_scolaire",
        ]
    ]
)

  numero_lycee    denomination_principale             patronyme code_commune  \
0     0031041R  LYCEE TECHNOLOGIQUE PRIVE           ANNA RODIER        03190
1     0030084A        LYCEE GENERAL PRIVE          SAINT BENOIT        03190
2     0030036Y              LYCEE GENERAL  THEODORE DE BANVILLE        03190
3     0030445T        LYCEE GENERAL PRIVE          SAINT-JOSEPH        03185
4     0030025L              LYCEE GENERAL       MADAME DE STAEL        03185
5     0030026M      LPO LYCEE DES METIERS         PAUL CONSTANS        03185
6     0030072M        LYCEE GENERAL PRIVE          SAINT PIERRE        03095
7     0030051P      LGT LYCEE DES METIERS        ALBERT LONDRES        03095
8     0031082K           LYCEE POLYVALENT        VALERY LARBAUD        03095
9     0030038A      LPO LYCEE DES METIERS           JEAN MONNET        03321

     commune  nombre_d_eleves rentree_scolaire
0    MOULINS               81       2019-01-01
1    MOULINS              119       2019-01-01
2    MOULINS             1034       2019-01-01
3  MONTLUCON               56       2019-01-01
4  MONTLUCON             1059       2019-01-01
5  MONTLUCON              938       2019-01-01
6     CUSSET              315       2019-01-01
7     CUSSET             1524       2019-01-01
8     CUSSET              227       2019-01-01
9     YZEURE              533       2019-01-01

In [19]:
url = "https://www.data.gouv.fr/api/1/datasets/r/98f3161f-79ff-4f16-8f6a-6d571a80fea2"

df = pd.read_csv(
    url,
    sep=";",
    encoding="latin1",
    skiprows=1,
    header=None,
    dtype=str,
    low_memory=False
)

df = df.rename(columns={
    1: "finess",
    3: "nom",
    7: "numero_voie",
    8: "type_voie",
    9: "libelle_voie",
    12: "code_commune_3",
    13: "code_departement",
    15: "code_postal_ville",
    18: "code_categorie",
    19: "libelle_categorie"
})

pharmacies = df[
    df["libelle_categorie"].str.contains("pharm|officine", case=False, na=False)
].copy()

pharmacies["code_insee"] = (
    pharmacies["code_departement"].str.zfill(2)
    + pharmacies["code_commune_3"].str.zfill(3)
)

pharmacies["adresse"] = (
    pharmacies["numero_voie"].fillna("") + " " +
    pharmacies["type_voie"].fillna("") + " " +
    pharmacies["libelle_voie"].fillna("")
).str.strip()

pharmacies_clean = pharmacies[[
    "finess",
    "nom",
    "adresse",
    "code_insee"
]]

#print(pharmacies_clean.head())
pharmacies_clean

,finess,nom,adresse,code_insee
27,010002285,NOUVELLE PHARMACIE DU CHAMP DE MARS,9 R ALEXANDRE BERARD,01004
28,010002301,GRANDE PHARMACIE D'AMBERIEU CENTRE,39 R ALEXANDRE BERARD,01004
30,010002335,PHARMACIE ORSET,625 AV LEON BLUM,01004
31,010002350,PHARMACIE DE LA GARE,68 AV ROGER SALENGRO,01004
32,010002384,PHARMACIE TRAN,RTE DE LA MAIRIE,01005
...,...,...,...,...
102855,980502470,PHARMACIE AL SHIFAA,54 R Des Manguiers,9F611
102878,980502769,PHARMACIE DES BADAMIERS,58 RTE des Badamiers,9F608
102879,980502785,PHARMACIE DES COCOTIERS,RTE de Ouangani,9F614
102898,980503064,PHARMACIE VANILLE,RTE Nationale 1,9F611
102932,980503643,PHARMACIE DE MAJICAVO,3 IMP COCOMZOURI,9F610